### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by kimboslice99** [saucecontrol/Brotli-IIS#12]
Are these instructions right?

Obviously start with
```
git clone https://github.com/saucecontrol/Brotli-IIS.git
git submodule update --init
md buildfiles\x64
pushd buildfiles\x64
```
But then this fails
```
 cmake -DCMAKE_INSTALL_PREFIX=.\install -DCMAKE_BUILD_TYPE=Release -DCMAKE_GENERATOR_PLATFORM=x64 -DCMAKE_C_FLAGS_RELEASE=/MT ..\..
```
So instead I run 
```
 cmake -DCMAKE_INSTALL_PREFIX=.\install -DCMAKE_BUILD_TYPE=Release -DCMAKE_GENERATOR_PLATFORM=x64 -DCMAKE_C_FLAGS_RELEASE=/MT ..\..\brotli
```
Which goes fine until I try to build in Visual Studio, where it then fails with 
```
Cannot open include file: 'brotli\encode.h': No such file or directory
```
It would be much appreciated if these instructions could be updated, or have I gone wrong somewhere?

Thanks

**Comment by saucecontrol** [comment]
I just ran through the process, and it looks like the only step I didn't include in the instructions is changing to the `brotli` directory created by the submodule init before running the cmake commands.  That will make the original path of `..\..` work from `buildfiles\x64`.

You didn't mention running the actual brotli build with the second cmake command listed
```
cmake --build buildfiles\x64 --config Release --target install
```

Did you do that part?  If so, you should see an install folder under `buildfiles\x64` with the headers and binaries in it.  If you ran the build command from the repo root, you can just move the `buildfiles` directory under `brotli`, and you should be set.

**Comment by kimboslice99** [comment]
Thanks for the super fast response! Well that solves the initial path issue however I still end up with the same issue in Visual Studio

```
git clone https://github.com/saucecontrol/Brotli-IIS.git
cd Brotli-IIS
git submodule update --init
cd brotli
md buildfiles\x64
pushd buildfiles\x64
cmake -DCMAKE_INSTALL_PREFIX=.\install -DCMAKE_BUILD_TYPE=Release -DCMAKE_GENERATOR_PLATFORM=Win32 -DCMAKE_C_FLAGS_RELEASE=/MT ..\..
popd
set CL=/D_CRT_SECURE_NO_WARNINGS=1
cmake --build buildfiles\x64 --config Release --target install
```

No install folder is found under `buildfiles\x64` after getting this far, and I suppose this is why Visual Studio is complaining

**Comment by saucecontrol** [comment]
That all looks right.  You'll have to wait for the first cmake command to actually finish before running the second, though.  If you try to throw all of those commands in a batch file, you'll need a pause or two in there.

**Comment by kimboslice99** [comment]
Part of the issue was Visual Studio 2022 prompt, I just ran all the same commands from a VS 2019 prompt and it went smoothly, I now have encode.h under `buildfiles\x64\install\include\brotli` however Visual Studio (2019) fails again with the same error `cannot open source file brotli\encode.h`

**Comment by saucecontrol** [comment]
Hmmm... I'm at a loss, then.  I just did the whole process with VS 2022 command prompt and then opened the vcxproj in VS 2022.  It asked me to update the SDK reference on open and then built fine.  I was on VS 2019 last time I updated the vcxproj, so that should be fine as well...

**Comment by kimboslice99** [comment]
Got it... had to provide direct paths to include and lib in the vcxproj file, strange however, makes me think something about our directory structure is vastly different, or Visual studio isnt working out of the right directory? Odd but nonetheless thank you for the help

**Comment by kimboslice99** [comment]
The latest brotli doesnt automatically compile static libs, heres the right cmake command to build static libs 
```
cmake -DCMAKE_INSTALL_PREFIX=.\install -DCMAKE_BUILD_TYPE=Release -DCMAKE_GENERATOR_PLATFORM=x64 -DBUILD_SHARED_LIBS=OFF -DCMAKE_C_FLAGS_RELEASE=/MT ..\..
```
Brotli also no longer appends -static to static libs so brotli.h needs to be adjusted

I do get quite a few warnings, though they dont seem to be an issue

Cmake
```
CMake Warning at CMakeLists.txt:264 (message):
  Test file tests/testdata/alice29.txt does not exist.

CMake Warning at CMakeLists.txt:264 (message):
  Test file tests/testdata/asyoulik.txt does not exist.

CMake Warning at CMakeLists.txt:264 (message):
  Test file tests/testdata/lcet10.txt does not exist.

CMake Warning at CMakeLists.txt:264 (message):
  Test file tests/testdata/plrabn12.txt does not exist.
```
Visual Studio
```
1>LINK : warning LNK4286: symbol 'exit' defined in 'libucrt.lib(exit.obj)' is imported by 'brotlienc.lib(encode.obj)'
1>LINK : warning LNK4286: symbol 'exit' defined in 'libucrt.lib(exit.obj)' is imported by 'brotlienc.lib(memory.obj)'
1>LINK : warning LNK4286: symbol 'malloc' defined in 'libucrt.lib(malloc.obj)' is imported by 'brotlienc.lib(memory.obj)'
1>LINK : warning LNK4286: symbol 'malloc' defined in 'libucrt.lib(malloc.obj)' is imported by 'brotlicommon.lib(platform.obj)'
1>LINK : warning LNK4286: symbol 'free' defined in 'libucrt.lib(free.obj)' is imported by 'brotlicommon.lib(platform.obj)'
```

**Comment by saucecontrol** [comment]
Yeah, I'd probably just switch over to using [vcpkg](https://github.com/microsoft/vcpkg) if updating to the new brotli version.  It'd be easier to automate the whole build process that way.

**Comment by kimboslice99** [comment]
Ah, fair enough

Have you considered creating a similar wrapper for the Zstd library?

**Comment by saucecontrol** [comment]
I hadn't, but that might be a good idea once browser support is enabled by default.  Looks like it's still behind an experiment flag everywhere for now. https://caniuse.com/?search=zstd

**Comment by kimboslice99** [comment]
So I went ahead and wrote [my own zstd compression plugin](https://github.com/kimboslice99/zstd-IIS)

I would appreciate any input you may have on how I did it, if you have some time to look

**Comment by saucecontrol** [comment]
I haven't really looked at libzstd, but if it works, it works 😃
